export const RETRIEVE_COUNTRIES = "RETRIEVE_COUNTRIES";
export const LOAD_COUNTRY = "LOAD_COUNTRY";

export const SELECTED_COUNTRIES = "SELECTED_COUNTRIES";
export const DESELECTED_VALUE = "DESELECTED_VALUE";

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const RETRIEVE_ACTIVITIES = "RETRIEVE_ACTIVITIES";
export const UPDATE_ACTIVITY = "UPTADE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const SEARCH = "SEARCH";
export const SORT = "SORT";
export const APPLY_FILTER = "APPLY_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const ERROR = "ERROR";
